package tools

import "github.com/matheustavarestrindade/mtt-harness/atom"

func (FileActions) InputSchema() atom.Schema {
	return schema(`{
		"type":"object", "additionalProperties":false,
		"properties":{
			"path":{"type":"string","minLength":1,"description":"One file or directory, relative to the instance workspace or absolute. Supply exactly one of path or paths. Existing symlink ancestors are resolved before path checks. Deletion preserves the final entry; other operations follow final links. Parent directories must exist. The workspace root cannot be deleted."},
			"paths":{"type":"array","minItems":1,"maxItems":32,"uniqueItems":true,"items":{"type":"string","minLength":1},"description":"1-32 files or directories that receive the same actions and return selection, in this order. Use instead of path. Duplicated resolved paths and overlapping mutation paths are rejected. All targets and output are prepared before any changes commit. Path gates are acquired in canonical order; commits run in input order. Filesystem commits are atomic per target, not across the batch. A commit I/O failure stops remaining targets and reports the failed target index and previously committed indexes (1-based). No automatic retry or rollback of committed targets. Preview output shares one 200-line/16-KiB budget across all targets."},
			"actions":{"type":"array","minItems":1,"maxItems":32,"description":"1-32 actions applied in order to each target; the chain and return options are shared, so repeat neither text nor operations per file. Each action sees earlier staged content and line numbers for that target. With return, only selected final output is emitted. Without return, inspections emit their data. All targets are prepared before commit: an action or preview failure changes none. Once commits start, each target is atomic; an I/O failure stops the batch and reports any committed target indexes. list actions cannot mix with file actions. Directory/link deletion needs a standalone delete action. Known edits need no preparatory read.","items":{
				"type":"object","additionalProperties":false,"required":["op"],"properties":{
					"op":{"type":"string","enum":["read","write","replace","append","prepend","delete","list"],"description":"read selects file text; write creates/replaces a file or lines; replace changes exact text; append/prepend add literal text at the end/start; delete removes the current file, a symbolic link itself, or an empty directory; list selects direct children. delete has no extra parameters, never removes recursively, and fails for a missing target. File deletion can be staged with other regular-file actions. A standalone link/directory delete requires return summary. File actions other than whole-file write need an existing file or preceding whole-file write. return read needs a file after the entire chain."},
					"content":{"type":"string","description":"Required for write, append and prepend only. Literal text without display labels or truncation notices. No automatic newline for whole-file write, append or prepend. Empty ranged write deletes selected lines. Non-empty ranged writes preserve the old block's closing LF/CRLF if content lacks its final LF."},
					"old_text":{"type":"string","minLength":1,"description":"Required only for replace: exact non-empty case-sensitive text to match. Whitespace and LF/CRLF must agree. Matches may span lines but cannot cross the selected line range. When the target is known from instructions or context, try the replacement directly with an appropriate return. No match stops the whole chain without changing the file. The error identifies the unmatched text (bounded excerpt for long values) and observed last-modified time when available."},
					"new_text":{"type":"string","description":"Required only for replace: literal replacement text. Empty deletes matches. Replacement content is not searched again; dollar signs/backslashes are not regex expressions."},
					"mode":{"type":"string","enum":["first","last","all"],"default":"first","description":"Only for replace: first (default) replaces the earliest match, last the latest, all every non-overlapping original match within the current selected range."},
					"start_line":{"type":"integer","minimum":1,"default":1,"description":"Only for read, write and replace: first line in the current staged file, 1-based inclusive. Omitted starts at 1. For write, omitting both line bounds replaces/creates the whole file; either bound requires existing lines."},
					"end_line":{"type":"integer","minimum":1,"description":"Only for read, write and replace: last inclusive line in the current staged file, at least start_line. Omitted means EOF. Read clamps an oversized end to EOF; edits reject it. A trailing LF adds no phantom line; an empty file has zero lines."},
					"start_byte":{"type":"integer","minimum":0,"default":0,"description":"Only for read: zero-based byte offset within start_line, excluding display labels. Omitted/0 starts at the line's beginning. Use the exact continuation offset supplied for a long line; it must address a byte inside the line and not split UTF-8. Later lines begin at byte 0."},
					"limit":{"type":"integer","minimum":1,"maximum":200,"default":100,"description":"Only for list: maximum direct directory entries, default 100, range 1-200. The shared 200-line/16-KiB output budget can reduce this. Hidden entries are included; symlinks are listed without following their targets."},
					"cursor":{"type":"string","default":"","maxLength":512,"description":"Only for list: opaque cursor from an earlier listing of this directory. Omitted/empty starts at the beginning. Entries are sorted by case-sensitive name. Do not construct cursors; concurrent directory changes can change subsequent pages."},
					"fields":{"type":"array","uniqueItems":true,"maxItems":5,"default":[],"items":{"type":"string","enum":["size","permissions","owner","group","modified"]},"description":"Only for list: optional metadata, in this order. Omitted/empty returns only F/D/L/S and the quoted entry name. size is the OS entry size in bytes, not recursive directory contents; permissions is the octal mode including special bits; owner/group are numeric UID/GID where available; modified is observed UTC RFC3339 time. Requested unavailable metadata is ?. These are filesystem attributes, not permission-approval settings. Links are not followed."}
				}
			}},
			"return":{"type":"object","additionalProperties":false,"required":["type"],"description":"Required for edits; optional for inspection. Applies to every target and replaces intermediate action output. Single-path calls return only selected data/status without banners or logs. Multiple-target read/list output has a short quoted-path label, diffs identify their own paths, and summary gives status counts. All targets share 200 lines/16 KiB including labels; a continuation reports a next target index when later targets are omitted. A preview failure occurs before any commit.","properties":{
				"type":{"type":"string","enum":["summary","diff","read","list"],"description":"summary returns Created, Updated, Deleted, Unchanged or OK for one path; for multiple targets it combines status counts. diff returns net before/after text diffs; deleted files use /dev/null as the final path. read returns final file text and fails for a deleted final file. list returns compact directory rows and requires list actions. Directory/link deletion supports summary only."},
				"context_lines":{"type":"integer","minimum":0,"maximum":100,"default":3,"description":"Only for diff: unchanged lines above/below each hunk. Default 3; 0 gives only changes; maximum 100. Diff comparisons over 256 KiB or 4000 combined lines and non-text content receive an omission notice; edits are never truncated."},
				"start_line":{"type":"integer","minimum":1,"default":1,"description":"Only for read: first final-file line to return after all actions, 1-based inclusive. Omitted starts at 1. Invalid ranges fail before committing edits."},
				"end_line":{"type":"integer","minimum":1,"description":"Only for read: last final-file line, inclusive and at least start_line. Omitted means EOF; oversized ends clamp to EOF; the shared preview budget still applies."},
				"start_byte":{"type":"integer","minimum":0,"default":0,"description":"Only for read: zero-based byte offset within start_line. Omitted/0 starts at its beginning. Use a supplied continuation cursor for long lines; never include display label bytes."},
				"limit":{"type":"integer","minimum":1,"maximum":200,"default":100,"description":"Only for list: maximum direct children, default 100, maximum 200, also subject to the shared output budget."},
				"cursor":{"type":"string","default":"","maxLength":512,"description":"Only for list: use an earlier opaque directory cursor; omitted/empty starts at the beginning."},
				"fields":{"type":"array","uniqueItems":true,"maxItems":5,"default":[],"items":{"type":"string","enum":["size","permissions","owner","group","modified"]},"description":"Only for list: metadata to add to each F/D/L/S and quoted-name row, in supplied order. Omitted/empty adds nothing. size is bytes; permissions is octal mode; owner/group are numeric UID/GID; modified is UTC RFC3339 time. Directory sizes are not recursive. ? means requested metadata unavailable; links are not followed."}
			}}
		},"required":["actions"],"oneOf":[{"required":["path"]},{"required":["paths"]}],
		"examples":[
			{"path":"notes.txt","actions":[{"op":"append","content":"endfile"}],"return":{"type":"read"}},
			{"path":"notes.txt","actions":[{"op":"read"}]},
			{"path":"src","actions":[{"op":"list"}]},
			{"path":"src","actions":[{"op":"list","fields":["permissions","owner","size"]}]},
			{"path":"notes.txt","actions":[{"op":"delete"}],"return":{"type":"summary"}},
			{"paths":["src/a.go","src/b.go"],"actions":[{"op":"replace","old_text":"oldName","new_text":"newName","mode":"all"}],"return":{"type":"summary"}},
			{"paths":["one.txt","two.txt"],"actions":[{"op":"append","content":"endfile"}],"return":{"type":"summary"}}
		]
	}`)
}
