package tools

import "github.com/matheustavarestrindade/mtt-harness/atom"

func (FileActions) InputSchema() atom.Schema {
	return schema(`{
		"type":"object", "additionalProperties":false,
		"properties":{
			"path":{"type":"string","minLength":1,"description":"One file or directory, relative to the instance workspace or absolute. For glob, this is the search root; the pattern is relative to it. Supply exactly one of path or paths. Existing symlink ancestors are resolved before path checks. Deletion preserves the final entry; other operations resolve the selected target. Glob never traverses links beneath its search root. Parent directories must exist. The workspace root cannot be deleted."},
			"paths":{"type":"array","minItems":1,"maxItems":32,"uniqueItems":true,"items":{"type":"string","minLength":1},"description":"1-32 files or directories that receive the same actions and return selection, in this order. Use instead of path. Duplicated resolved paths and overlapping mutation paths are rejected. All targets and output are prepared before any changes commit. Path gates are acquired in canonical order; commits run in input order. Filesystem commits are atomic per target, not across the batch. A commit I/O failure stops remaining targets and reports the failed target index and previously committed indexes (1-based). No automatic retry or rollback of committed targets. Preview output shares one 200-line/16-KiB budget across all targets."},
			"actions":{"type":"array","minItems":1,"maxItems":32,"description":"1-32 ordered actions shared across targets. Each target has its own staged content and line numbers. With return, only selected final output is emitted; otherwise inspections emit their data. All targets prepare before commit: an action or preview failure changes none. Commit I/O failures stop the batch and report committed target indexes. Directory discovery (list/glob) may be combined together, but cannot mix with file-content actions or mutations. Directory/link deletion needs one delete action. Glob finds paths only and never expands mutation targets. Known edits need no preparatory read.","items":{
				"type":"object","additionalProperties":false,"required":["op"],"properties":{
					"op":{"type":"string","enum":["read","write","replace","append","prepend","delete","list","glob"],"description":"read selects file text; write creates/replaces a file or lines; replace changes exact text; append/prepend add literal text; delete removes a file, link itself, or empty directory; list selects direct children; glob matches descendant paths beneath the selected directory. list/glob may be combined with each other but not file actions. Glob returns paths only; matches never become mutation targets automatically. delete never recurses. File deletion can be staged with other regular-file actions; link/directory deletion needs one delete action and return summary. Whole-file write can create a file; other file actions need a file. return read needs a final file."},
					"content":{"type":"string","description":"Required for write, append and prepend only. Literal text without display labels or truncation notices. No automatic newline for whole-file write, append or prepend. Empty ranged write deletes selected lines. Non-empty ranged writes preserve the old block's closing LF/CRLF if content lacks its final LF."},
					"old_text":{"type":"string","minLength":1,"description":"Required only for replace: exact non-empty case-sensitive text to match. Whitespace and LF/CRLF must agree. Matches may span lines but cannot cross the selected line range. When the target is known from instructions or context, try the replacement directly with an appropriate return. No match stops the whole chain without changing the file. The error identifies the unmatched text (bounded excerpt for long values) and observed last-modified time when available."},
					"new_text":{"type":"string","description":"Required only for replace: literal replacement text. Empty deletes matches. Replacement content is not searched again; dollar signs/backslashes are not regex expressions."},
					"mode":{"type":"string","enum":["first","last","all"],"default":"first","description":"Only for replace: first (default) replaces the earliest match, last the latest, all every non-overlapping original match within the current selected range."},
					"start_line":{"type":"integer","minimum":1,"default":1,"description":"Only for read, write and replace: first line in the current staged file, 1-based inclusive. Omitted starts at 1. For write, omitting both line bounds replaces/creates the whole file; either bound requires existing lines."},
					"end_line":{"type":"integer","minimum":1,"description":"Only for read, write and replace: last inclusive line in the current staged file, at least start_line. Omitted means EOF. Read clamps an oversized end to EOF; edits reject it. A trailing LF adds no phantom line; an empty file has zero lines."},
					"start_byte":{"type":"integer","minimum":0,"default":0,"description":"Only for read: zero-based byte offset within start_line, excluding display labels. Omitted/0 starts at the line's beginning. Use the exact continuation offset supplied for a long line; it must address a byte inside the line and not split UTF-8. Later lines begin at byte 0."},
					"limit":{"type":"integer","minimum":1,"maximum":200,"default":100,"description":"Only for list/glob: maximum entries or matches, default 100, range 1-200. The shared 200-line/16-KiB output budget can reduce this. Hidden entries are included; symlinks are not traversed."},
					"cursor":{"type":"string","default":"","maxLength":32768,"description":"Only for list/glob: opaque continuation from the same directory and unchanged query. Omitted/empty starts at the beginning. list permits at most 512 bytes; glob permits 32768. Entries are sorted by case-sensitive relative path. Do not construct cursors; filesystem changes can affect subsequent pages."},
					"fields":{"type":"array","uniqueItems":true,"maxItems":5,"default":[],"items":{"type":"string","enum":["size","permissions","owner","group","modified"]},"description":"Only for list/glob: optional metadata in supplied order. Omitted/empty returns F/D/L/S and the quoted name or relative path. size is bytes, not recursive directory contents; permissions is octal mode with special bits; owner/group are numeric UID/GID; modified is observed UTC RFC3339 time. ? means requested metadata unavailable. These are filesystem attributes, not permission-approval settings. Links are not followed."},
					"pattern":{"type":"string","minLength":1,"maxLength":1024,"description":"Required only for glob: case-sensitive Doublestar pattern, 1-1024 characters, matched against paths relative to path/each paths directory. Use / separators. * and ? stay within one path component; ** as a component matches zero or more directories; [abc], [a-z], [!abc] and {go,md} alternatives are supported. A backslash escapes a wildcard. Examples: **/*.go, src/**/*.{ts,svelte}. Absolute paths and parent traversal are invalid. Root itself is not listed. Patterns do not search file contents."},
					"exclude":{"type":"array","maxItems":16,"default":[],"items":{"type":"string","minLength":1,"maxLength":1024},"description":"Only for glob: zero to 16 exclusion patterns using the same syntax and root. Omitted/empty excludes nothing; .gitignore is not loaded. Matching directories are pruned with their descendants. Example: [\"**/node_modules/**\",\"**/.git/**\"]."},
					"kind":{"type":"string","enum":["file","directory","link","all"],"default":"file","description":"Only for glob: file (default) matches regular files; directory matches directories; link matches symlink entries; all includes these and special entries. Symlink directories are never traversed, even when named literally in a pattern. Hidden names are included unless excluded explicitly."}
				}
			}},
			"return":{"type":"object","additionalProperties":false,"required":["type"],"description":"Required for edits; optional for inspection. Applies to every target and replaces intermediate action output. Single-path calls return only selected data/status without banners or logs. Multiple-target read/list output has a short quoted-path label, diffs identify their own paths, and summary gives status counts. All targets share 200 lines/16 KiB including labels; a continuation reports a next target index when later targets are omitted. A preview failure occurs before any commit.","properties":{
				"type":{"type":"string","enum":["summary","diff","read","list","glob"],"description":"summary gives status; diff gives net text changes; read gives final file text. list gives direct directory entries; glob gives matching descendant paths. list/glob output requires directory actions; glob requires its own pattern. Omit return for ordinary glob/list inspection. Multiple targets share the output budget. Directory/link deletion supports summary only."},
				"context_lines":{"type":"integer","minimum":0,"maximum":100,"default":3,"description":"Only for diff: unchanged lines above/below each hunk. Default 3; 0 gives only changes; maximum 100. Diff comparisons over 256 KiB or 4000 combined lines and non-text content receive an omission notice; edits are never truncated."},
				"start_line":{"type":"integer","minimum":1,"default":1,"description":"Only for read: first final-file line to return after all actions, 1-based inclusive. Omitted starts at 1. Invalid ranges fail before committing edits."},
				"end_line":{"type":"integer","minimum":1,"description":"Only for read: last final-file line, inclusive and at least start_line. Omitted means EOF; oversized ends clamp to EOF; the shared preview budget still applies."},
				"start_byte":{"type":"integer","minimum":0,"default":0,"description":"Only for read: zero-based byte offset within start_line. Omitted/0 starts at its beginning. Use a supplied continuation cursor for long lines; never include display label bytes."},
				"limit":{"type":"integer","minimum":1,"maximum":200,"default":100,"description":"Only for list/glob: maximum entries or matches, default 100, maximum 200, subject to the shared output budget."},
				"cursor":{"type":"string","default":"","maxLength":32768,"description":"Only for list/glob: opaque continuation for the same root and query. Omitted/empty starts at the beginning. list permits 512 bytes; glob permits 32768. Concurrent filesystem changes can affect later pages."},
				"fields":{"type":"array","uniqueItems":true,"maxItems":5,"default":[],"items":{"type":"string","enum":["size","permissions","owner","group","modified"]},"description":"Only for list/glob: opt-in metadata in supplied order. Default adds nothing to F/D/L/S and quoted relative path. size is bytes; permissions octal mode; owner/group numeric UID/GID; modified UTC RFC3339 time. ? means unavailable. Directory sizes are not recursive; links are not followed."},
				"pattern":{"type":"string","minLength":1,"maxLength":1024,"description":"Required for return glob: relative, case-sensitive Doublestar pattern with / separators, *, **, ?, character classes and brace alternatives. Same syntax and 1-1024-character limit as a glob action. Root itself is excluded; absolute and parent-traversal paths are invalid."},
				"exclude":{"type":"array","maxItems":16,"default":[],"items":{"type":"string","minLength":1,"maxLength":1024},"description":"Only for return glob: optional exclusion patterns relative to the root, same syntax as pattern. Matching directories are pruned. Default empty; .gitignore is not loaded."},
				"kind":{"type":"string","enum":["file","directory","link","all"],"default":"file","description":"Only for return glob: regular files (default), directories, symlink entries, or all entry types. Hidden entries are included; symlink directories are never traversed."}
			}}
		},"required":["actions"],"oneOf":[{"required":["path"]},{"required":["paths"]}],
		"examples":[
			{"path":"notes.txt","actions":[{"op":"append","content":"endfile"}],"return":{"type":"read"}},
			{"path":"notes.txt","actions":[{"op":"read"}]},
			{"path":"src","actions":[{"op":"list"}]},
			{"path":"src","actions":[{"op":"list","fields":["permissions","owner","size"]}]},
			{"path":"notes.txt","actions":[{"op":"delete"}],"return":{"type":"summary"}},
			{"paths":["src/a.go","src/b.go"],"actions":[{"op":"replace","old_text":"oldName","new_text":"newName","mode":"all"}],"return":{"type":"summary"}},
			{"paths":["one.txt","two.txt"],"actions":[{"op":"append","content":"endfile"}],"return":{"type":"summary"}},
			{"path":".","actions":[{"op":"glob","pattern":"**/*.{go,md}","exclude":["**/.git/**","**/vendor/**"]}]}
		]
	}`)
}
